# Generated by Django 5.1.4 on 2024-12-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrityGuard_app', '0006_collabration_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_text',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback_files/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_message',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
