# Generated by Django 5.1.4 on 2025-02-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrityGuard_app', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Legal_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Legal_cases', to='IntegrityGuard_app.user'),
        ),
    ]
