# Generated by Django 5.1.4 on 2025-02-06 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrityGuard_app', '0011_case_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_file', models.FileField(blank=True, null=True, upload_to='Evidence_files/')),
                ('provided_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='IntegrityGuard_app.case')),
                ('provided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_evidence', to='IntegrityGuard_app.user')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='IntegrityGuard_app.user')),
            ],
        ),
    ]
