# Generated by Django 5.1.4 on 2025-04-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrityGuard_app', '0012_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='internal_Investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_Investigator', to='IntegrityGuard_app.user'),
        ),
    ]
