# Generated by Django 5.1.4 on 2025-04-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrityGuard_app', '0016_rename_assigned_date_case_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Assigned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
