# Generated by Django 5.1.4 on 2025-04-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntegrityGuard_app', '0017_alter_case_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
